//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WmsViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WmsViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMS Viewer.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow {
            get {
                object obj = ResourceManager.GetObject("Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-update of the image.
        /// </summary>
        internal static string AutoUpdate {
            get {
                return ResourceManager.GetString("AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRS:.
        /// </summary>
        internal static string Crs {
            get {
                return ResourceManager.GetString("Crs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download maps from internet.
        /// </summary>
        internal static string DownloadMaps {
            get {
                return ResourceManager.GetString("DownloadMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download sublayers as one image.
        /// </summary>
        internal static string DownloadOneImage {
            get {
                return ResourceManager.GetString("DownloadOneImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Drag {
            get {
                object obj = ResourceManager.GetObject("Drag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URI address of new WMS service:.
        /// </summary>
        internal static string EnterNewWmsUri {
            get {
                return ResourceManager.GetString("EnterNewWmsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not in XML format!.
        /// </summary>
        internal static string FileNotInXmlFormat {
            get {
                return ResourceManager.GetString("FileNotInXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image address:.
        /// </summary>
        internal static string ImageAddress {
            get {
                return ResourceManager.GetString("ImageAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image format:.
        /// </summary>
        internal static string ImageFormat {
            get {
                return ResourceManager.GetString("ImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted text is not a valid URI!.
        /// </summary>
        internal static string InsertedTextNotValidUri {
            get {
                return ResourceManager.GetString("InsertedTextNotValidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer description:.
        /// </summary>
        internal static string LayerDescription {
            get {
                return ResourceManager.GetString("LayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer title:.
        /// </summary>
        internal static string LayerTitle {
            get {
                return ResourceManager.GetString("LayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Main {
            get {
                object obj = ResourceManager.GetObject("Main", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New WMS.
        /// </summary>
        internal static string NewWms {
            get {
                return ResourceManager.GetString("NewWms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New WMS service.
        /// </summary>
        internal static string NewWmsWindowTitle {
            get {
                return ResourceManager.GetString("NewWmsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not valid XML file!.
        /// </summary>
        internal static string NotValidXmlFile {
            get {
                return ResourceManager.GetString("NotValidXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol version:.
        /// </summary>
        internal static string ProtocolVersion {
            get {
                return ResourceManager.GetString("ProtocolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen coordinates.
        /// </summary>
        internal static string ScreenCoordinates {
            get {
                return ResourceManager.GetString("ScreenCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMS address:.
        /// </summary>
        internal static string ServiceAddress {
            get {
                return ResourceManager.GetString("ServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service description:.
        /// </summary>
        internal static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service title:.
        /// </summary>
        internal static string ServiceTitle {
            get {
                return ResourceManager.GetString("ServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported CRSs:.
        /// </summary>
        internal static string SupportedCrs {
            get {
                return ResourceManager.GetString("SupportedCrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent color:.
        /// </summary>
        internal static string TransparentColor {
            get {
                return ResourceManager.GetString("TransparentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading the WMS capabilites!.
        /// </summary>
        internal static string WmsCapabilitiesDownloadingError {
            get {
                return ResourceManager.GetString("WmsCapabilitiesDownloadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZoomIn {
            get {
                object obj = ResourceManager.GetObject("ZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZoomOut {
            get {
                object obj = ResourceManager.GetObject("ZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
